### ISSUE TITLE
Measures should be actual measures as per Fiscal Data Package

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-viewer#62]
Currently, each Viewer state has a "Facts" measure, and in general it is not clear if the measures object is being displayed correctly. 

Testing with some of the BOOST data packages, ensure that the measures UI actually displays the measures as per the Fiscal Data Package.

cc @akariv

**Comment by akariv** [comment]
I think the UI should take the list of measures from the `measures` section in the model - this section describes the existing columns, while the `aggregates` parameter also has information on the requested aggregate function to apply to the values.

The `aggregates` section is as a list of possible aggregate functions you may use (a-la SQL). Here, it's possible to choose either to sum on the `amount` column or use a `count(*)` method - in which case the # of records will be returned instead of a sum of a column. The aggregate has a ‘measure’ part and a ‘function’ part. the function could also be (in the future) ‘max’, ‘average’, ‘std’  etc.

**Comment by borysyuk** [comment]
Done!
